name: OWASP ZAP Scan

on:
  pull_request:
    branches:
      - main  # Trigger ZAP scan on PRs targeting the `main` branch
  push:
    branches:
      - main  # Or trigger on push to the `main` branch

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Python (optional, if your application is Python-based)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: 'https://www.medium.com/'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: report_html.html  # Path to the ZAP scan report generated
